services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: trankhacbinhduong
      POSTGRES_PASSWORD: trankhacbinhduong
      POSTGRES_DB: nuxt-pg
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: